name: Code Coverage

on: ['push', 'pull_request']


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - run: gem update --system
    - run: gem install compass

    - uses: actions/setup-node@v2
      with:
          node-version: 12.x
    - run: npm install-test

    - uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
